server:
  servlet:
    context-path: /xos
    application-display-name: xos

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/xos?useUnicode=true&useSSL=false&characterEncoding=utf8&autoReconnect=true&rewriteBatchedStatements=TRUE&failOverReadOnly=false
    password: 123456
    username: root
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 5
    minIdle: 5
    maxActive: 20
    timeBetweenEvictionRunsMillis: 40000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: true
    testOnReturn: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,log4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: true
  servlet:
    multipart:
      # 上传一个文件最大值，默认为1MB
      max-file-size: 10MB
      # 上传多个文件最大值，50MB，默认为10MB
      max-request-size: 100MB
xos:
  default-avator-url: http://www.baidu.com
  hadoop:
    file-system:
      user: hadoop
      url: hdfs://xuezhiqiang-PC:8020
      block-size: 134217728
      default-capacity: 1073741824
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  config-location: classpath:mybatis-config.xml
  type-aliases-package: my.xzq.xos.server.model
